#!/bin/bash
apk add --no-cache ruby git curl ncurses ruby-json
git clone --depth 1 https://github.com/Linuxbrew/brew.git ~/.linuxbrew
cd ~/.linuxbrew
git apply $ASSETS_DIR/linuxbrew.patch
mkdir -p ~/.linuxbrew/Library/Taps/homebrew/homebrew-core
cd ~/.linuxbrew/Library/Taps/homebrew/homebrew-core
git init
git remote add origin git://github.com/homebrew/homebrew-core.git
export PATH="$HOME/.linuxbrew/bin:$PATH"
