#!/bin/bash
apk add --no-cache ruby git curl ncurses ruby-json

# for mac
git clone --depth 1 https://github.com/Homebrew/brew.git /home/homebrew/.linuxbrew/homebrew
cd /home/homebrew/.linuxbrew
mkdir bin
ln -s /home/homebrew/.linuxbrew/homebrew/bin/brew /home/homebrew/.linuxbrew/bin
mkdir -p homebrew/Library/Taps/homebrew/homebrew-core
cd homebrew/Library/Taps/homebrew/homebrew-core
git init
git remote add origin https://github.com/Homebrew/homebrew-core.git


# for linux
git clone --depth 1 https://github.com/Homebrew/brew.git /home/linuxbrew/.linuxbrew/homebrew
cd /home/linuxbrew/.linuxbrew
mkdir bin
ln -s /home/linuxbrew/.linuxbrew/homebrew/bin/brew /home/linuxbrew/.linuxbrew/bin
mkdir -p homebrew/Library/Taps/homebrew/homebrew-core
cd homebrew/Library/Taps/homebrew/homebrew-core
git init
git remote add origin https://github.com/Homebrew/linuxbrew-core.git
